version: '3'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_NAME=math_exam_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - PORT=8080
      - JWT_SECRET=mathdev
      - AWS_S3_ACCESS_KEY_ID=AKIAVJHWGBQMYWZM7GEV
      - AWS_S3_SECRET_ACCESS_KEY=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
      - AWS_S3_BUCKET=math-exam 
    depends_on:
      - db
    volumes:
      - ./api:/api
      - /api/node_modules

  backoffice:
    build: ./backoffice
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API=http://localhost:8080
      - WATCHPACK_POLLING=true
    depends_on:
      - api
    stdin_open: true
    volumes:
      - ./backoffice:/backoffice
      - /backoffice/node_modules

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=math_exam_dev
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  db:
    driver: local
  pgadmin_data:
    driver: local